TECH_SKILLS = {
    "python",
    "sql",
    "azure",
    "aws",
    "docker",
    "kubernetes",
    "terraform",
    "linux",
    "git",
    "github",
    "azure devops",
    "jenkins",
    "airflow",
    "databricks",
    "spark",
    "pyspark",
    "adf",
    "synapse",
    "power bi",
    "tableau",
    "snowflake",
    "redshift",
    "postgresql",
    "mysql",
    "mongodb",
    "fastapi",
    "django",
    "flask",
    "java",
    "c#",
    ".net",
    "react",
    "next.js",
    "typescript",
    "javascript",
}